### ISSUE TITLE
PayPalAPI is not defined

### ISSUE THREAD

**Issue by zaneticIT** [Dreamvention/paypal#8]
Uncaught ReferenceError: PayPalAPI is not defined
    at <anonymous>:3:1
    at b (jquery-3.6.0.min.js:2:866)
    at He (jquery-3.6.0.min.js:2:48373)
    at S.fn.init.append (jquery-3.6.0.min.js:2:49724)
    at S.fn.init.<anonymous> (jquery-3.6.0.min.js:2:50816)
    at $ (jquery-3.6.0.min.js:2:32425)
    at S.fn.init.html (jquery-3.6.0.min.js:2:50494)
    at Object.<anonymous> (jquery-3.6.0.min.js:2:85141)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)

![image](https://user-images.githubusercontent.com/63416994/230512019-1ac36649-d377-4264-94ca-29f43c56b7c2.png)

**Comment by zaneticIT** [comment]
Opencart 4.0.1.1
